### PR TITLE
support in-line cooments #5 

### PR DESCRIPTION
**Pull request by bootjp**
Thank you for a very good library.
When I looked at the issues, there were some that were not supported, so I sent a Pull Request.

However, there are performance concerns with this implementation.

It will be a bit complicated, but should I change the processing between the cases with in-line comment and without it?

### CODE REVIEW

**Comment by jaytaylor** [comment]
Hi Bootjp,

Thanks for your kind words :)

Can you elaborate a bit on the performance concerns?  How large of hosts files are you trying to consume with this?

Not sure if I'm missing something, because this PR seems reasonable AFAICT.

**Comment by bootjp** [comment]
Because of the addition of for loop, performance degradation occurs compared to previous implementations.
https://github.com/jaytaylor/go-hostsfile/blob/c2f3f874717facbcff18e7105d0218a1ee7f72c6/hosts.go#L33

Running the attached gist benchmark causes some performance degradation.
If this performance degradation is acceptable, merge this code
https://gist.github.com/bootjp/1760e97654ae0ca16f1b5fbb9997e375
```
$ go test -bench . -benchmem -count=4
goos: linux
goarch: amd64
cpu: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
BenchmarkNow-6             65882             16646 ns/op           10696 B/op        188 allocs/op
BenchmarkNow-6             74793             18446 ns/op           10696 B/op        188 allocs/op
BenchmarkNow-6             54309             19370 ns/op           10696 B/op        188 allocs/op
BenchmarkNow-6             63922             18401 ns/op           10696 B/op        188 allocs/op
BenchmarkPrevious-6        77395             16398 ns/op            9816 B/op        159 allocs/op
BenchmarkPrevious-6        79010             16220 ns/op            9816 B/op        159 allocs/op
BenchmarkPrevious-6        78464             16643 ns/op            9816 B/op        159 allocs/op
BenchmarkPrevious-6        77016             16496 ns/op            9816 B/op        159 allocs/op
PASS
ok      _/home/bootjp/src/go-hostsfile/tmp      12.245s
```

**Comment by bootjp** [comment]
@jaytaylor How about this?
I would like you to merge if there is no problem with a little performance degradation.

**Comment by jaytaylor** [comment]
@bootjp LGTM, thank you!

**Pull request merged**
